### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by kotenok2000** [opengs/uashield#194]
Memory usage increases if you leave it running for several hours.
Memory usage increased to 2.6 gb in 5 hours

**Comment by krsh-off** [comment]
I'm seeing the same behavior. 
<img width="999" alt="image" src="https://user-images.githubusercontent.com/12412972/160155067-eb2616c2-bb0a-49e0-9964-1c3c4a0a5cf1.png">

**Comment by opengs** [comment]
@krsh-off do you have automatic "workers" count? maybe its because program increases its workers count to some very big values (like 2k workers)?

**Comment by opengs** [comment]
@krsh-off how much memory do you have on this machine?

**Comment by krsh-off** [comment]
@opengs Actually no, it's visa versa. I was setting 128 workers and it was continuously decreasing while consuming more memory. The screenshot I provided is for Docker run without arguments, so it's having 32 workers and proxy enabled. The amount of workers is also decreasing till ~16-17, but memory behavior is the same. Traffic inbound/outbound is lower than 100 kb/s because all sites are DOWN OR BLOCKED. 

I have 1 CPU and 1 GB RAM on DigitalOcean, a $5/month instance. Multiple instances.

**Comment by krsh-off** [comment]
@opengs Interesting note, and 10:00 I disabled proxy. With a proxy, it was almost always DOWN OR BLOCKED and memory usage was increasing, after disabling the proxy I start getting 200 and 403 HTTP codes and memory usage has stabilized.
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/12412972/160231758-43bd49f3-d5b4-459f-b13e-e5cd3b35f751.png">

**Comment by opengs** [comment]
this is expected behavior with automatic workers scheduler. But with 1gb ram we have to set upped boundary of workers. (2k is too much for 1GB of RAM). Also we will check proxy http agent for memory leak.

**Comment by Ai-rin** [comment]
Confirm, same here. I think previous versions didn't have this problem, but now uashield
is next to unusable for me - it tends to seize all available memory.

**Comment by galitz** [comment]
Same here.  I've been running on a raspberry pi 3 with 1G RAM without crashes until the update to 0.0.28.  Currently I get only about 15min of useable time before it bogs down.

**Comment by MikronT** [comment]
Can confirm this bug still exists in the latest version 0.0.30. With proxy on, parallelism goes up and up

![Screenshot 2022-04-08 211343](https://user-images.githubusercontent.com/45333177/162499233-96e21a16-b27f-4a23-987a-825a4c6f2310.png)

Then the app cuts down the number of workers to about 120 and everything starts all over again. But the biggest problem is that the app crashes sometimes due to "heap out of memory" errors

![image](https://user-images.githubusercontent.com/45333177/162500432-2f62b5a8-bdd8-42f6-b0d8-a2cb9bfb55c6.png)

**Comment by opengs** [comment]
In the version 0.0.31 you can set upper limit of threads, so it will not grow indefinitely.

**Comment by opengs** [comment]
Looks like problem finally gone in 0.0.31 . Based on targets, program uses different ammount of memory (more memory if targets alive). In setup below, most of the targets are down, app takes 200-300mb of RAM. We have been testing this for 30 minutest. Memory usage stays stable. 

![image](https://user-images.githubusercontent.com/34212339/162605927-3417aecc-11c7-4947-bf89-d7815f5fd5ed.png)

When target alive, memory usage can be high, because app creates buffer for storing response. This response can be several megabytes in size :( . For something like 1-2k of threads its huge. I will check how to immediately delete response body (without buffering), but its definitely not in this issue.
