### ISSUE TITLE
Always get the latest version

### ISSUE THREAD

**Issue by alexnest-ua** [opengs/uashield#208]
Please, make your releases with the same program names, that in auto-scripts, we could just get the latest version from one link (otherwise I'm already tired of always changing it [here](https://auto-ddos.notion.site/auto-ddos/DDoS-new-b6f56bf8e4cd4eebb5abfc85cbd77f93) ...)

For example: https://github.com/disbalancer-project/main/releases/latest/download/launcher-disbalancer-go-client-linux-amd64

All you need to do is make the following structure: https://github.com/disbalancer-project/main/releases
Everything else I will do myself

Thanks

**Comment by opengs** [comment]
Sorry for the late response. We are using electron updater for auto-updates and I really don't know if those types of changes will not ruin this. If you just give the link for the old version it will auto-update to the newest. Or you can add a link to the releases page so the user can choose a file. At this point, I will not experiment with this :( , because if something will go wrong, all the users will have to manually update.
