### ISSUE TITLE
attacks on my computer

### ISSUE THREAD

**Issue by AlexeiKaplenko** [opengs/uashield#225]
I've been using CyberShield for some time on my Linux machine with static IP and observed in logs that it's been attacked. There were attempts to guess the password for my sudo account. The current solution I found was to change the IP address contacting the Internet provider. What are other options to avoid the risk of being attacked in the future using your software?

P.S. I need static IP to connect remotely to my machine

**Comment by CA3iR0** [comment]
VPN.

I also detected some russian IPs trying to hack my Macintosh, but my provider has dynamic IPs that change everytime I reboot my router. MUAHAHAH

**Comment by opengs** [comment]
Hej, sorry for the long response. I think the best option is VPN, because proxies are not 100% safe (they may leak your public IP address).

We should definitely provide this information in the manual. Thank you for pointing this out.

If your static machine is without a graphical interface, you have to find a VPN with CLI installation. A lot of VPN providers also give OpenVPN config, and you can create a container with OpenVPN inside. Unfortunately, we don't have it implemented "from the box" at the moment. I don't think we will implement this in the near future because it will require OpenVPN manual configuration. So we have to figure out how to do this for users that don't have much knowledge of this / make instructions / etc. But we have this in plans. For now, try to use the custom VPN of your choice.
